image: node:latest
cache:
  paths:
    - node_modules/
before_script:
    - npm -g install yarn
    - yarn
stages:
    - test
test:
    stage: test
    only:
        - latest
    script:
        - npm test
